[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel"]

build-backend = 'setuptools.build_meta'

[ tool.gilesbot ]
  [ tool.gilesbot.pull_requests ]
    enabled = true
